### ISSUE TITLE
Prismarine Proxy doesn't suport versions above 1.16

### ISSUE THREAD

**Issue by Vakore** [PrismarineJS/prismarine-proxy#22]
1.16.1, 1.16.4, and 1.17 are not supported by prismarine proxy. Trying to join as 1.16 from 1.16.1 will work for a bit, but then will disconnect. I think this is due to the protocols for those versions not being implemented somewhere, or something is missing. I was told that protocols need an example so that they know how to use the pakcets, so it could have something to do with that.

**Comment by rom1504** [comment]
do you have a specific thing you ran along with an error?

**Comment by Vakore** [comment]
ERROR:
```
(node:11220) UnhandledPromiseRejectionWarning: Error: Packets for version 1.16.1 aren't stored. This can be fixed by dumping them adding them to the verMap if similar packets are stored.
    at getPacket (C:\Users\UserIsMe\node_modules\prismarine-proxy\src\instant_connect_proxy.js:11:28)
    at InstantConnectProxy.onLogin (C:\Users\UserIsMe\node_modules\prismarine-proxy\src\instant_connect_proxy.js:33:34)
    at Server.<anonymous> (C:\Users\UserIsMe\node_modules\prismarine-proxy\src\instant_connect_proxy.js:25:44)
    at Server.emit (events.js:315:20)
    at loginClient (C:\Users\UserIsMe\node_modules\minecraft-protocol\src\server\login.js:128:12)
    at C:\Users\UserIsMe\node_modules\minecraft-protocol\src\server\login.js:88:9
    at C:\Users\UserIsMe\node_modules\yggdrasil\src\utils.js:73:15
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11220) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```



CODE:
```
const { InstantConnectProxy } = require('prismarine-proxy')
const proxy = new InstantConnectProxy({
  loginHandler: (client) => {
    return {
        username: "username",
        password: "password",
        auth: "microsoft",
    };
  },
  clientOptions: {
    host: 'kiwiland.wtf',
    version: '1.16.1'
  },
  serverOptions: {
    version: '1.16.1',
  }
})


proxy.on('incoming', (data, meta, toClient, toServer) => { // packets incoming from the server to the client
   console.log(meta.name);
  //if (meta.name === 'world_particles') return
  toClient.write(meta.name, data) // send the packet to the client
})

proxy.on('outgoing', (data, meta, toClient, toServer) => { // packets outgoing from the client to the server
  var sendPacket = true;
  if (meta.name === 'chat') {
    console.log(data.message);
    if (data.message == "glow") {
      sendPacket = false;
    }
  }
  if (sendPacket) {
    toServer.write(meta.name, data); // send the packet to the client
  }
})
```

**Comment by Vakore** [comment]
Run the code, wait for the proxy to show that it has booted up on the IP 'localhost'(it'll take longer than expected for some reason, probably related to the issue), then once it finally shows up connect and see the error in the console.

Running node --trace-warnings did not seem to give any more information.

```
const verMap = {
    "1.16.1":"1.16",
};
```

I tried adding the above code near the beginning of the program and it did not fix the error.

**Comment by rom1504** [comment]
ok it's due to https://github.com/PrismarineJS/minecraft-packets not containing the latest versions

**Comment by u9g** [comment]
It's been fixed in the latest commit

**Comment by u9g** [comment]
Now released.
